app/authentication/urls.py
from django.urls import path

import authentication.views as views

urlpatterns = [
    path('login/', views.auth_login),
    path('logout/', views.auth_logout),
    path('register/', views.auth_register),
    path('register/request-access/', views.request_registration),
    path('register/manage-request/', views.manage_registration_request),
    path('activate/', views.activate),
    path('invite/', views.invite)
]

app/chat/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('<str:room_name>/', views.room, name='room'),
]

app/songspotting/urls.py
import re

from django.conf import settings
from django.contrib import admin
from django.contrib.staticfiles.storage import staticfiles_storage
from django.shortcuts import redirect
from django.urls import include, path, re_path
from django.views.static import serve

urlpatterns = [
    path('favicon.ico', lambda request: redirect(staticfiles_storage.url('favicon.ico'), permanent=True)),
    path('admin/', admin.site.urls),
    path('auth/', include('authentication.urls')),
    path('chat/', include('chat.urls')),
    path('radio/', include('radio.urls')),
    path('user/', include('user.urls')),
    path('', lambda request: redirect(settings.HOMEPAGE)),

    # Serve media files
    re_path(
        r'^%s(?P<path>.*)$' % re.escape(settings.MEDIA_URL.lstrip('/')),
        view=serve,
        kwargs={'document_root': settings.MEDIA_ROOT}
    )
]

app/authentication/models.py
from django.db import models
import os

from django.conf import settings

import binascii

import authentication


class Token(models.Model):
    """
    An access token that is associated with a user.  This is essentially the same as the token model from Django REST Framework
    """
    key = models.CharField(max_length=40, primary_key=True)
    user = models.OneToOneField(
        settings.AUTH_USER_MODEL,
        related_name="token",
        on_delete=models.CASCADE
    )
    created = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.key:
            self.key = authentication.generate_token()
        return super(Token, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.key


class RegistrationRequest(models.Model):
    """
    A request to create a new user.
    """
    email = models.EmailField(unique=True)
    message = models.TextField(blank=True)
    token = models.CharField(max_length=40, blank=True, null=False)
    timestamp = models.DateTimeField(auto_now_add=True)

    def save(self, *args, **kwargs):
        if not self.token:
            self.token = authentication.generate_token()
        return super(RegistrationRequest, self).save(*args, **kwargs)

    def __unicode__(self):
        return self.email

app/authentication/forms.py
# -*- coding: utf-8 -*-
from django import forms

from authentication.models import RegistrationRequest


class RegistrationRequestForm(forms.ModelForm):
    class Meta:
        model = RegistrationRequest
        fields = ('email', 'message')

app/authentication/views.py
# -*- coding: utf-8 -*-
import contextlib
import json
import smtplib
from django.conf import settings
from django.contrib.auth import authenticate, login, logout, get_user_model
from django.contrib.auth.decorators import login_required, user_passes_test
from django.contrib.auth.password_validation import validate_password
from django.core.cache import cache
from django.core.exceptions import ValidationError
from django.core.mail import send_mail
from django.http.response import (
    HttpResponse,
    HttpResponseBadRequest,
    HttpResponseRedirect
)
from django.shortcuts import render
from django.template.loader import render_to_string
from django.views.decorators.http import require_http_methods

import authentication
import authentication.forms

from authentication.models import RegistrationRequest

User = get_user_model()


@require_http_methods(['GET', 'POST'])
def auth_login(request):
    if request.method == 'GET':
        return _render_login_page(request)
    elif request.method == 'POST':
        return _login(request)


def auth_logout(request):
    logout(request)
    return HttpResponseRedirect(settings.HOMEPAGE)


def _render_login_page(request):
    _next = request.GET.get('next', settings.HOMEPAGE)
    return render(request, 'login_form.html', context={'next': _next})


def _login(request):
    try:
        credentials = json.loads(request.body)
    except json.JSONDecodeError:
        credentials = request.POST.dict()
    persistent_session = credentials.pop('_persistent', False)
    user = authenticate(
        request,
        username=credentials.get('username'),
        password=credentials.get('password')
    )
    if not user:
        return HttpResponse('Invalid credentials', status=401, reason='Unauthorized')
    login(request, user)
    if not persistent_session:
        request.session.set_expiry(0)
    return HttpResponse('Login successful')


@require_http_methods(['GET', 'POST'])
def request_registration(request):
    if request.method == 'GET':
        return render(
            request,
            'request_registration.html',
            context={'form': authentication.forms.RegistrationRequestForm()}
        )
    elif request.method == 'POST':
        form = authentication.forms.RegistrationRequestForm(request.POST)
        if form.is_valid():
            form_data = form.cleaned_data
            registration_request = RegistrationRequest(
                email=form_data['email'],
                message=form_data['message'],
                token=authentication.generate_token()
            )
            return _handle_registration_request(request, registration_request)
        else:
            return HttpResponseBadRequest(form.errors['email'][0])


def _handle_registration_request(request, registration):
    if User.objects.filter(email=registration.email):
        return HttpResponseBadRequest("A user with this email already exists")
    with contextlib.suppress(RegistrationRequest.DoesNotExist):
        RegistrationRequest.objects.get(email=registration.email)
        return HttpResponseBadRequest(
            "You already requested access to the site using this email. Please, wait "
            "for an approval by the administrators."
        )
    _send_registration_request_email(request, registration)
    registration.save()
    return HttpResponse(
        "Request successfully submitted. You will receive a feedback soon."
    )


def _send_registration_request_email(request, registration):
    manage_request_url = request.build_absolute_uri(
        location='/auth/register/manage-request/?t={}'.format(
            registration.token
        )
    )
    # Notify the user that request has been sent
    try:
        send_mail(
            subject="Your registration request",
            message=None,
            from_email=None,
            recipient_list=[registration.email],
            html_message=render_to_string(
                'confirm_registration_request_received_email.html',
                context={'manage_request_url': manage_request_url}
            )
        )
    except smtplib.SMTPRecipientsRefused:
        # Ignore malformed or non existing email addresses
        pass
    # Send registration request to admin
    manage_request_url += '&admin'
    send_mail(
        subject="New registration request",
        message=None,
        from_email=None,
        recipient_list=[settings.DEFAULT_FROM_EMAIL],
        html_message=render_to_string(
            'registration_request_email.html',
            context={
                'registration_request': registration,
                'manage_request_url': manage_request_url
            }
        )
    )


@require_http_methods(['GET', 'POST', 'DELETE'])
def manage_registration_request(request):
    try:
        registration_request = RegistrationRequest.objects.get(
            token=request.GET.get('t')
        )
    except RegistrationRequest.DoesNotExist:
        if request.method == 'GET':
            return render(request, '404.html', status=404)
        return HttpResponse(
            "Registration request not found, probably it has been already deleted.",
            status=404
        )
    if request.method == 'POST':
        if not request.user.is_staff:
            return HttpResponse(
                "You are not allowed to perform this operation.",
                status=401
            )
        _accept_registration_request(request, registration_request)
        return HttpResponse("Registration request accepted.")
    elif request.method == 'DELETE':
        _reject_registration_request(request, registration_request)
        return HttpResponse("Registration request rejected.")
    if 'admin' in request.GET:
        auth_wrapper = user_passes_test(lambda user: user.is_staff)
    else:
        auth_wrapper = user_passes_test(lambda user: True)
    get_response = auth_wrapper(render)
    return get_response(
        request,
        'manage_registration_request.html',
        context={'registration_request': registration_request}
    )


def _accept_registration_request(request, registration):
    invite_token = authentication.generate_token()
    register_url = request.build_absolute_uri(
        location='/auth/register/?t={}'.format(
            invite_token
        )
    )
    _send_invitation_link(registration.email, register_url)
    registration.delete()
    cache.set(invite_token, True)


def _reject_registration_request(request, registration):
    register_url = request.build_absolute_uri(
        location='/auth/register/request-access/'
    )
    send_mail(
        subject="Your registration request",
        message=None,
        from_email=None,
        recipient_list=[registration.email],
        html_message=render_to_string(
            'registration_request_rejected_email.html',
            context={'register_url': register_url}

        )
    )
    registration.delete()


@require_http_methods(['GET', 'POST'])
def auth_register(request):
    if request.method == 'GET':
        return _render_register_page(request)
    elif request.method == 'POST':
        return _register(request)


def _render_register_page(request):
    token = request.GET.get('t')
    if token is None:
        return HttpResponseRedirect('request-access/')
    if not _validate_token(token):
        return render(request, '401.html', status=401)
    return render(request, 'register_form.html', context={'token': token})


def _validate_token(token):
    return cache.get(token, False)


def _register(request):
    token = request.GET.get('t')
    if not _validate_token(token):
        return render(request, '401.html', status=401)
    try:
        user_data = json.loads(request.body)
    except json.JSONDecodeError:
        user_data = request.POST.dict()
    user = User(
        username=user_data['username'],
        email=user_data['email'],
        is_active=False
    )
    try:
        validate_password(user_data['password'], user=user)
    except ValidationError as e:
        return HttpResponseBadRequest(e.messages[0])
    user.set_password(user_data['password'])
    try:
        _validate_unique_user(user)
    except ValidationError as e:
        return HttpResponseBadRequest(str(e))
    account_activation_token = authentication.generate_token()
    activation_url = request.build_absolute_uri(
        location='/auth/activate/?t={}'.format(
            account_activation_token
        )
    )
    message = render_to_string(
        'activation_email.html',
        context={'activation_url': activation_url}
    )
    try:
        user.email_user(
            subject='Account activation',
            message='',
            html_message=message
        )
    except smtplib.SMTPRecipientsRefused:
        return HttpResponseBadRequest('Check your email')
    user.save()
    cache.set(account_activation_token, user.get_username())
    cache.delete(token)
    return HttpResponse('User {} created successfully'.format(user.get_username()))


def _validate_unique_user(user):
    try:
        user.validate_unique()
    except ValidationError as e:
        raise ValidationError('The username is already taken') from e
    if User.objects.filter(email=user.email).exists():
        raise ValidationError('The email is already taken')


@require_http_methods(['GET', 'POST'])
def activate(request):
    token = request.GET.get('t')
    username = cache.get(token)
    try:
        user = User.objects.get_by_natural_key(username)
    except User.DoesNotExist:
        return render(request, '404.html', status=404)
    user.is_active = True
    user.save()
    cache.delete(token)
    return render(
        request, 'account_activation.html'
    )


def _send_invitation_link(email, register_url):
    send_mail(
        subject='Invitation link',
        message=None,
        from_email=None,
        html_message=render_to_string(
            'invitation_email.html',
            context={'register_url': register_url}

app/authentication/templates/account_activation.html
{% load static %}
<html lang="en">
    {% include "header.html" %}
    <body class="text-center">
        <main role="main" class="container">
              <h2 class="mt-5" id=login_title>Welcome to SongSpotting!</h2>
              <p class="lead" id="please_register">Your account has been successfully activated</p>
            <div>
                <span></span>
                <button class="btn btn-lg btn-light btn-block" type="button" id='loginButton'>Proceed to login</button>
            </div>
        </main>
        <script>

        document.getElementById("loginButton").addEventListener("click", loginAction);

        function loginAction() {
            window.location.href = "{{ settings.LOGIN_URL }}"
        }
        </script>
    </body>
    {% include "footer.html" %}
</html>

app/authentication/templates/activation_email.html
{% load static %}
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title> SongSpotting - Activate account</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <script src="https://use.fontawesome.com/bc59cc0bbf.js"></script>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="icon" type="image/x-icon" href="{% static 'songspotting/favicon.ico' %}"/>  <!--Load icon from static files-->

        <style>
        html, body {
          height: 100%;
        }

        body {
          display: -ms-flexbox;
          display: -webkit-box;
          display: flex;
          -ms-flex-align: center;
          -ms-flex-pack: center;
          -webkit-box-align: center;
          align-items: center;
          -webkit-box-pack: center;
          justify-content: center;
          padding-top: 40px;
          padding-bottom: 40px;
          background-color: #f5f5f5;
        }
        </style>

    </head>
    <body class="text-center">
        <main role="main" class="container">
            <h2 class="mt-5" id=login_title>Welcome to SongSpotting!</h2>
            <div>
                <p class="lead" id="please_register">Click here to activate your account:</p>
                <a  class="btn btn-light" href="{{activation_url}}" style="background-color: #f57c00; color:white; ">
                    Activate account
                </a>
            </div>
            <p class="url" id="copy_invite_link">If the link does not work, copy and past this URL in your browser: {{activation_url}}</p>
            <p class="lead">This message has been sent to you by a SongSpotting administrator, you can reply directly to this email for any question.</p>
        </main>

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

app/authentication/templates/confirm_registration_request_received_email.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title> SongSpotting - Registration Request</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <script src="https://use.fontawesome.com/bc59cc0bbf.js"></script>
        <script src="https://code.jquery.com/jquery-3.4.1.min.js"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>

        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="icon" type="image/x-icon" href="{% static 'songspotting/favicon.ico' %}"/>  <!--Load icon from static files-->

        <style>
        html, body {
          height: 100%;
        }

        body {
          display: -ms-flexbox;
          display: -webkit-box;
          display: flex;
          -ms-flex-align: center;
          -ms-flex-pack: center;
          -webkit-box-align: center;
          align-items: center;
          -webkit-box-pack: center;
          justify-content: center;
          padding-top: 40px;
          padding-bottom: 40px;
          background-color: #f5f5f5;
        }
        </style>

    </head>
    <body class="text-center">
        <main role="main" class="container">
            <h2 class="mt-5" id=login_title>Your registration request</h2>
            <div>
                <p class="lead">
                    We received a user registration request for this email.<br>
                    You will soon receive a confirmation email, notifying you about the status of your request.<br>
                    Please allow 1-2 days, if you haven't received anything after this period you can reply directly to this email for more information.

                </p>
            </div>
            <p class="lead">
                <i>If you think this is a mistake and you never requested access to the site, please use the following link to cancel the request:
                <a href="{{ manage_request_url }}">{{ manage_request_url }}</a></i>
            </p>
        </main>
    </body>
</html>

app/authentication/templates/invitation_email.html
{% load static %}
<!doctype html>
<html lang="en">
    <head>
        <meta charset="utf-8">
        <title> SongSpotting - Invite</title>
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
        <script src="https://use.fontawesome.com/bc59cc0bbf.js"></script>
        <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link rel="icon" type="image/x-icon" href="{% static 'songspotting/favicon.ico' %}"/>  <!--Load icon from static files-->

        <style>
        html, body {
          height: 100%;
        }

        body {
          display: -ms-flexbox;
          display: -webkit-box;
          display: flex;
          -ms-flex-align: center;
          -ms-flex-pack: center;
          -webkit-box-align: center;
          align-items: center;
          -webkit-box-pack: center;
          justify-content: center;
          padding-top: 40px;
          padding-bottom: 40px;
          background-color: #f5f5f5;
        }
        </style>

    </head>
    <body class="text-center">
        <main role="main" class="container">
            <h2 class="mt-5" id=login_title>Welcome to SongSpotting!</h2>
            <div>
                <p class="lead">Click here to create a new account:</p>
                <a  class="btn btn-light" href="{{register_url}}" style="background-color: #f57c00; color:white; ">
                    Create account
                </a>
            </div>
            <p class="url" id="copy_invite_link">If the link does not work, copy and past this URL in your browser: {{register_url}}</p>
            <p class="lead">This message has been sent to you by a SongSpotting administrator, you can reply directly to this email for any question.</p>
        </main>

        <script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
        <script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
    </body>
</html>

app/authentication/templates/invite_users.html
{% load static %}
<html>
    {% include "header.html" %}
    <style>
    </style>
    <body>
        <main role="main">
            <h1 class="mt-5">Invite other people to SongSpotting!</h1>
            <hr>
            <form action="#" name="form_email">
                {% csrf_token %}
                <h1 class="h3 mb-3 font-weight-normal">Invite by email:</h1>
                <div style="float:inside;">
                    <label for="inputEmail" class="sr-only">email</label>
                    <input type="text" id="inputEmail" name="email" class="form-control" placeholder="email" required autofocus>
                </div>
                <div style="float: inside">
                    <button class="btn btn-lg btn-light btn-block" type="button" id='inviteEmail'>Send invite</button>
                </div>
                <br>
                <div style="float: inside">
                    <a id="email_state" hidden></a>
                </div>
            </form>
            <hr>
            <form action="#" name="form_link">
                {% csrf_token %}
                <h1 class="h3 mb-3 font-weight-normal">Invite by link:</h1>
                <div style="float: inside">
                    <button class="btn btn-lg btn-light btn-block" type="button" id='inviteLink'>Generate link</button>
                </div>
                <div style="float: inside" id="link_state" hidden>
                    <p>Use this invitation link:<br><a id="invite_url"></a></p>
                </div>
            </form>
        </main>

        <script>
        document.getElementById("inputEmail").addEventListener("click", resetStyle);
        document.getElementById("inputEmail").addEventListener("change", resetStyle);
        function resetStyle() {
                this.style = $(".form-control")
        }

        document.getElementById("inviteEmail").addEventListener("click", sendEmail);
        document.getElementById("inviteLink").addEventListener("click", generateLink);

        function sendEmail() {
            document.getElementById("email_state").hidden = true;
            document.getElementById("email_state").style = $('a');

            let email = document.getElementById('inputEmail').value;

            if (email === "") {
                document.getElementById('inputEmail').style.borderColor = "red";
            }
            if (email !== "") {
                let data = {
                    "email": email
                };

                let xmlhttp_post = new XMLHttpRequest();   // new HttpRequest instance
                xmlhttp_post.onreadystatechange = function() {
                    if (this.readyState === 4) {
                        document.getElementById("email_state").innerText = this.responseText;
                        document.getElementById("email_state").hidden = false;
                    }
                }
                xmlhttp_post.open("POST", "/auth/invite/"); // Method and Target
                xmlhttp_post.setRequestHeader("Content-Type", "application/x-www-form-urlencoded"); //Headers
                xmlhttp_post.send($('form[name=form_email]').serialize()); //From JSON Object to String
            }
        }
        function generateLink() {
            document.getElementById("link_state").hidden = true;
            let xmlhttp_post = new XMLHttpRequest();   // new HttpRequest instance
            xmlhttp_post.onreadystatechange = function() {
                if (this.readyState === 4) {
                    document.getElementById("invite_url").innerText = this.responseText;
                    document.getElementById("invite_url").href = this.responseText;
                    document.getElementById("link_state").hidden = false;
                }
            }
            xmlhttp_post.open("POST", "/auth/invite/"); // Method and Target
            xmlhttp_post.setRequestHeader("Content-Type", "application/x-www-form-urlencoded"); //Headers
            xmlhttp_post.send($('form[name=form_link]').serialize()); //From JSON Object to String
        }
        </script>
    </body>
    {% include "footer.html" %}
</html>

app/authentication/templates/request_registration.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
    {% include "header.html" %}
    <style>
    </style>
    <body>
        <main role="main">
            <h1 class="mt-5">User registration</h1>
            <p class="mt-5">In order to access the site, you need to log in.
                Users can be created only with a permission from the site administrators.<br>
                Input your email below to request access to the site. Leave also a message telling who you are.
                You will receive a response soon notifying you about the status of your request.<br><br>

                Your email will only be used for communications about the site (no spam) and it will never be shared
                with anyone else.<br>
                If we reject your registration request, your email will be immediately deleted.
                It is always possible to delete a user to remove ALL it's data from the server.
            </p>
            <hr>
            <form name="form" style="color:white;">
                {% csrf_token %}
                <h3>
                    <label>Request access:</label>
                </h3>
                <ul>
                    <li>
                        <label for="id_email">Email:</label>
                        <input type="email" name="email" maxlength="254" required id="id_email">
                    </li>
                    <li>
                        <label for="id_message">Message:</label>
                        <textarea name="message" id="id_message" style="resize: none;"></textarea>
                    </li>
                </ul>
                <div>
                    <p id="confirmation" hidden></p>
                </div>
                <button class="btn btn-lg btn-light" id="sendRequestButton">Send request</button>
            </form>
        </main>
    <script>
        document.addEventListener(
            "keydown",
            function(event) {
                if (event.code === "Enter") {
                    document.getElementById("sendRequestButton").click();
                }
            }
        );

        $("form").submit(sendRequest);

        function sendRequest(event) {
            event.preventDefault();
            document.getElementById("confirmation").hidden = true;
            document.getElementById("confirmation").style = $('p');
            document.getElementById('sendRequestButton').disabled = true;
            let xmlhttp_post = new XMLHttpRequest();   // new HttpRequest instance
            xmlhttp_post.addEventListener("readystatechange", processResponse);

            function processResponse(event) {
                if (this.readyState === 4) {
                    if (this.status >= 200 && this.status < 500) {
                        document.getElementById("confirmation").innerText = this.responseText;
                        if (this.status >= 400) {
                            document.getElementById('confirmation').style.color = "red";
                        }
                    }
                    else {
                        document.getElementById("confirmation").innerText = "An error occurred, please contact an administrator";
                        document.getElementById('confirmation').style.color = "red";
                    }
                    document.getElementById("confirmation").hidden = false;
                    document.getElementById('sendRequestButton').disabled = false;
                }
            }

            xmlhttp_post.open("POST", window.location.href); // Method and Target
            xmlhttp_post.setRequestHeader("Content-Type", "application/x-www-form-urlencoded"); //Headers
            xmlhttp_post.send($('form').serialize());  // URL encode form data
        }
        </script>
    </body>
    {% include "footer.html" %}
</html>